---
title: 'Tissue-specific insulin resistance is characterized distinct gut microbial profiles in a population with overweight or obesity'
author: "A. Umanets"
date: "`r date()`"
output:
  html_document: default
  pdf_document: default
---


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
#-------------------------------------------------------------------------------
# Load libraries and set the environment 
#-------------------------------------------------------------------------------
set.seed(549794)

# Load libraries 
libs.list <- c("phyloseq", "tidyverse", "psych", "metagenomeSeq",
               "vegan", "broom", "gridExtra", "ComplexHeatmap", 
               "RColorBrewer", "circlize")

for (i in libs.list) {library(i, character.only = TRUE)}

rm(list = c("i", "libs.list"))

source("R/phy_taxa_filter.R")

source("R/phy_shorten_tax_names.R")

source("R/local_functions.R")
```


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
# Variables 
#-------------------------------------------------------------------------------
# Metabolites with less than (see below) prevalence are filtered out. 
metab.prev <- 0.75

cor.estim <- 0.3

cor.estim.plot <- 0.5

otu.prev.cut <- 0.25

cor.qval <- 0.1

#-------------------------------------------------------------------------------
# Micorbiota associated data
#-------------------------------------------------------------------------------
# Read in phyloseq and remove the control group 
ps1 <- readRDS("out/phyloseqs/ps1_2gr.rds") 

ps1.genus <- readRDS("out/phyloseqs/ps1_genus_2gr.rds")

ps.meta <- ps1 %>% 
              sample_data() %>% 
              as.matrix() %>% 
              as.data.frame()  %>% 
              mutate(across(all_of(c("Phenotype", "Center", "Sex")), as.factor), 
                     across(Age, as.numeric))

# Collect out tables in a list 
otu.tabs.ls <- list()

otu.tabs.ls[["asv.css"]] <-  ps1 %>% 
                                phy_taxa_filter(., 
                                                prev_fraction = otu.prev.cut,
                                                group_col = "Phenotype") %>% 
                                phyloseq_to_metagenomeSeq(.) %>% 
                                cumNorm(., p=cumNormStatFast(.)) %>% 
                                MRcounts(., norm=TRUE, log=TRUE) %>% 
                                t() %>% 
                                as.data.frame()

otu.tabs.ls[["genus.css"]] <-  ps1.genus %>% 
                               phy_taxa_filter(., 
                                                prev_fraction = otu.prev.cut,
                                                group_col = "Phenotype") %>% 
                                phyloseq_to_metagenomeSeq(.) %>% 
                                cumNorm(., p=cumNormStatFast(.)) %>% 
                                MRcounts(., norm=TRUE, log=TRUE) %>% 
                                t() %>% 
                                as.data.frame()


#-------------------------------------------------------------------------------
# Metabolites associated data 
#-------------------------------------------------------------------------------
# All metabolites
metabol.data <- read.csv("data/metabolites/DSM_complite_ciw1.csv", strip.white = TRUE) %>% 
                  'colnames<-'(gsub("\\.", "_", colnames(.))) %>% 
                  'colnames<-'(sub("X", "", colnames(.))) %>% 
                  'colnames<-'(gsub("_(?=,|$)", "", colnames(.), perl = TRUE)) %>% 
                  rename(Xanthine = anthine) %>% 
                  mutate(across(-Participant_ID, as.numeric)) %>%
                  mutate(Participant_ID = paste0(Participant_ID, "CIW1")) %>% 
                  column_to_rownames("Participant_ID") %>% 
                  select(which(colSums(is.na(.))/nrow(.) <= (1-metab.prev)))

# Hand selected metabolites
metabol.sel.vec <- readLines("data/metabolites/selected_metabolites.txt") %>% 
                              gsub("-", "_", .)

# Make list blood metabolites data 
blood.ls <- list()

blood.ls[["blood.hand.picked"]] <- metabol.data[, intersect(colnames(metabol.data), 
                                                      metabol.sel.vec)] %>% 
                                          replace(is.na(.), 0)

blood.ls[["blood"]] <- metabol.data %>% 
                          replace(is.na(.), 0)


blood.ls[["blood.hand.picked.log"]] <- metabol.data[, intersect(colnames(metabol.data), 
                                                      metabol.sel.vec)] %>% 
                                      replace(is.na(.), 0.001) %>% 
                                      log10(.)

blood.ls[["blood.log"]] <- metabol.data %>% 
                              replace(is.na(.), 0.001) %>% 
                              log10(.)


# SCFA data --------------------------------------------------------------------
scfa.data <- read.csv("data/metabolites/scfa_data.csv")

scfa.data.ls <- list()

for(i.type in c("fecal", "plasma", "GLP")) {
  
  scfa.inst <- scfa.data %>% 
                    select(all_of(c("Participant_ID", 
                                    grep(i.type, colnames(.), 
                                         value = TRUE, 
                                         ignore.case=TRUE)))) %>% 
                    mutate(Participant_ID = paste0(Participant_ID, "CIW1")) %>% 
                    column_to_rownames("Participant_ID") %>% 
                    filter(if_any(everything(), ~ !is.na(.)))
  
  col.name <- paste0("SCFS.", i.type)
  
  ps.meta <- scfa.inst %>% 
               mutate(!!col.name := "Yes", 
                      SeqID = rownames(.)) %>% 
               select(all_of(c(col.name, "SeqID"))) %>% 
               left_join(ps.meta, ., by = "SeqID")
  
  scfa.data.ls[[i.type]] <- scfa.inst
}
#-------------------------------------------------------------------------------

# Adjust metadata 
ps.meta <- left_join(ps.meta, data.frame(SeqID = rownames(metabol.data), 
                                         DSM.metabol = "Yes"), by = "SeqID") %>% 
            mutate(ColNam = SeqID) %>% 
            column_to_rownames("ColNam")


write.csv(ps.meta, "out/metadata_full.csv")


# Taxa significantly different between LIR and MIR 
sig.taxa.asv <- read.csv("out/LIR_MIR_asv_sig_DA.csv")

sig.taxa.genus <- read.csv("out/LIR_MIR_genus_sig_DA.csv")

# CCA formula 
cca.form <- "Phenotype + Condition(Sex + Age + Center)"

meta.blood.samp <- intersect(rownames(metabol.data), rownames(ps.meta))

# Groups color
col.gr <- RColorBrewer::brewer.pal(3, "Dark2")[c(2,3)]

names(col.gr) <- levels(ps.meta[, "Phenotype"])

```


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
################################################################################
# Wilcox test 
################################################################################

wil.blood.res <- wilcox_plus(numer_df = blood.ls$blood[meta.blood.samp, ], 
                       meta_data = ps.meta[meta.blood.samp, ], 
                       group_col = "Phenotype")

wil.blood.res <- wil.blood.res %>% 
                      dplyr::filter(ID %in% metabol.sel.vec) %>% 
                      mutate(qval_select = p.adjust(p_value, "BH")) %>% 
                      select(all_of(c("qval_select", "ID"))) %>% 
                      left_join(wil.blood.res, ., by = "ID") %>% 
                      mutate(qval_all = p.adjust(p_value, "BH")) %>% 
                      arrange(p_value)

write.csv(wil.blood.res, "out/wil_blood_res.csv")
```


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
################################################################################
# CCA ordination
################################################################################
cca.res.all <- list()

for (i.met.tab in names(blood.ls)) {
  
  dir.path <- paste0("out/CCA/", gsub("\\.", "_", i.met.tab), "/")
  
  dir.create(dir.path, recursive = TRUE)
  
  met.tab.inst <- blood.ls[[i.met.tab]]
    
  cca.res <- cca_test_plot(data = met.tab.inst[meta.blood.samp, ], 
                                            metadata = ps.meta[meta.blood.samp, ], 
                                            formula = cca.form, 
                                            color_col = "Phenotype", 
                                            bi_var_to_plot = "Phenotype")
  write_csv(tidy(cca.res$anoca_cca), 
              paste0(dir.path, "anovaCCA_", i.met.tab, ".csv"))
  
  ggsave(paste0(dir.path, "biplot_", i.met.tab, ".png"), 
                plot = cca.res$bi_plot + 
                scale_color_manual(values = col.gr[1:2]), 
         width = 5, height = 3.5, dpi = 600)
  
  ggsave(paste0(dir.path, "triplot_", i.met.tab, ".png"), 
                plot = cca.res$tri_plot + 
                scale_color_manual(values = col.gr[1:2]), 
         width = 5, height = 3.5, dpi = 600)
  
  cca.res.all[[i.met.tab]] <- cca.res
                              
}

```


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
################################################################################
# Correlation analysis
################################################################################
cor.metab.ls <- c(scfa.data.ls, blood.ls[2])
  
cor.res.all <- list()

for (i.metab in names(cor.metab.ls)) {
    
    metab.inst <- cor.metab.ls[[i.metab]]
  
    over.samp <- intersect(rownames(ps.meta), rownames(metab.inst))
    
    otu.tabs.ls.f <- recurse_lapply(otu.tabs.ls, function(x){x[over.samp, ]})
    
    cor.res.all[[i.metab]] <- bulk_corr_matrix(otu_tabs_list = otu.tabs.ls.f, 
                                       meta_data = ps.meta[over.samp, ], 
                                       second_df = metab.inst[over.samp, ], 
                                       strata_cols_meta = "Phenotype", 
                                       prev_cut_offs = 0)
  
}


#saveRDS(cor.res.all, file = "out/metabolites_corr_res.RDS")
#cor.res.all <- readRDS("out/metabolites_corr_res.RDS")
```


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
# Filter out correlations with low estimates 
cor.res.all.q <- recurse_lapply(cor.res.all, 
                               function(x) {x %>% 
                                           # select(-qval) %>% 
                                           mutate(CorID = paste0(Taxa, "--",
                                           Corre_vector))}) %>% 
                recurse_lapply(., 
                               function(x) {x %>% 
                                            filter(abs(estimate) >= cor.estim) %>% 
                                            mutate(qval_f = p.adjust(p.value, 
                                                                   method = "BH")) %>% 
                                            select(CorID, qval_f) %>% 
                                            left_join(x, ., by = "CorID") %>% 
                                            mutate(qval_p = ifelse(qval_f <= cor.qval, 
                                                                   "*", ""))}) %>% 
                unlist(recursive = FALSE)


cor.res.all.q.sig <- recurse_lapply(cor.res.all.q, function(x) {x %>% 
                                          filter(abs(estimate) >= cor.estim, 
                                                 qval_f <= cor.qval)})

dir.create("out/cor_res")

for(i.name in names(cor.res.all.q.sig)) {
  
  cor.res.all.q.sig[[i.name]] %>% 
    bind_rows() %>% 
    write.csv(., 
              paste0("out/cor_res/", 
                     gsub("--0", "", i.name), ".csv"))
  
}
```            


```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
#-------------------------------------------------------------------------------
# Plot correlation heatmaps 
#-------------------------------------------------------------------------------
cor.res.all.mat <- cor.res.all.q %>% 
                      recurse_lapply(., function(x){ x %>% 
                                          select(Taxa, estimate, 
                                                 Corre_vector, Strata) %>% 
                                          pivot_wider(names_from = Corre_vector, 
                                                      values_from = estimate)}) 


sup.df <- data.frame(ID = unique(gsub("\\..*", "", names(cor.res.all.mat))), 
                     color = brewer.pal(length(names(cor.metab.ls)), "Set2"), 
                     size = c(2.5, 2.5, 1.5, 10)) %>% 
            column_to_rownames("ID")



heat.ls <- list()

for (i.mat in names(cor.res.all.mat)) {
  
  mat.inst <- cor.res.all.mat[[i.mat]] %>% 
                bind_rows() 
  
  n.inst <- gsub("\\..*", "", i.mat)
  
  ht_opt$TITLE_PADDING = unit(c(5.5, 5.5), "points")
  
  heat.ls[[i.mat]] <- Heatmap(select(mat.inst, -all_of(c("Taxa", "Strata"))), 
                       column_title = n.inst, 
                      column_title_gp = gpar(fill = sup.df[n.inst, "color"], 
                                             col = "black", 
                                             border = "black", 
                                             fontsize = 12, 
                                             fontface = "bold"), 
                       show_row_dend = FALSE, name = "Estimate", 
                       width = unit(sup.df[n.inst, "size"], "cm"), 
                       height = unit(10, "cm"), 
                       row_split = mat.inst$Strata, 
                       show_column_names = FALSE, 
                       show_column_dend = FALSE, 
                       show_row_names = FALSE)

  }

heat.asv <- heat.ls$`blood.asv.css--0` + 
            heat.ls$`plasma.asv.css--0` + 
            heat.ls$`fecal.asv.css--0` + 
            heat.ls$`GLP.asv.css--0` 



heat.genus <- heat.ls$`blood.genus.css--0` + 
            heat.ls$`plasma.genus.css--0` + 
            heat.ls$`fecal.genus.css--0` + 
            heat.ls$`GLP.genus.css--0`


dir.create("out/fig/heat_maps/", recursive = TRUE)

png("out/fig/heat_maps/full_heat_asv.png", width = 25, height = 20, units = "cm", res = 600)
draw(heat.asv, merge_legend = TRUE)
dev.off()

png("out/fig/heat_maps/full_heat_genus.png", width = 25, height = 20, units = "cm", res = 600)
draw(heat.genus, merge_legend = TRUE)
dev.off()
```

```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
################################################################################
# Correlation with significant taxa 
################################################################################

for (i.lvl in c("asv", "genus")) {
    
    cor.res.p <- cor.res.all.q %>% 
                .[grep(i.lvl, names(.), value = TRUE)]
    
    if(i.lvl == "asv") {
      
      cor.res.p <- recurse_lapply(cor.res.p, 
                                  function(x){filter(x, Taxa %in% sig.taxa.asv$Taxa)})
    } else {
      
      cor.res.p <- recurse_lapply(cor.res.p, 
                                  function(x){filter(x, Taxa %in% sig.taxa.genus$Taxa)})
      
    }

      cor_heat_plot(cor_func_res = cor.res.p, 
              sup_df = sup.df, 
              out_folder = paste0("out/fig/heat_sig_", cor.estim, "est/", i.lvl), 
              qval_f_cut = cor.qval, 
              estimate_cut = cor.estim)
}

```

```{r , message=FALSE, warning=FALSE, prompt=FALSE, results='hide', echo=FALSE}
################################################################################
# Correlation with significant taxa and selected boold metabolites
################################################################################

cor.res.sel.q <- cor.res.all.q

cor.res.sel.q[grep("blood", 
              names(cor.res.sel.q))] <- recurse_lapply(cor.res.sel.q[grep("blood",
                                                      names(cor.res.sel.q))], 
                                function(x) { x %>% filter(Corre_vector %in% metabol.sel.vec)})


for (i.lvl in c("asv", "genus")) {
    
    cor.res.p <- cor.res.sel.q %>% 
                .[grep(i.lvl, names(.), value = TRUE)]
    
    if(i.lvl == "asv") {
      
      cor.res.p <- recurse_lapply(cor.res.p, 
                                  function(x){filter(x, Taxa %in% sig.taxa.asv$Taxa)})
    } else {
      
      cor.res.p <- recurse_lapply(cor.res.p, 
                                  function(x){filter(x, Taxa %in% sig.taxa.genus$Taxa)})
      
    }

      cor_heat_plot(cor_func_res = cor.res.p, 
              sup_df = sup.df, 
              out_folder = paste0("out/fig/heat_sig_sel_", cor.estim, "est/", i.lvl), 
              qval_f_cut = cor.qval, 
              estimate_cut = cor.estim)
}

```


```{r , message=FALSE, warning=FALSE, results='hide', echo=FALSE}

strat.res.plots <- list()

  
  for(i.l2 in names(cor.res.all.q.sig)) {
    
    res.long <- cor.res.all.q.sig[[i.l2]] %>%
                            bind_rows() %>% 
                            mutate(qval = qval_f)

    if(grepl("asv", i.l2)) {
      
      res.long <- recurse_lapply(res.long, 
                                  function(x){filter(x, Taxa %in% sig.taxa.asv$Taxa)})
    } else {
      
      res.long <- recurse_lapply(res.long, 
                                  function(x){filter(x, Taxa %in% sig.taxa.genus$Taxa)})
      
    }
    
    otu.tab <- otu.tabs.ls.f[[gsub("--.*", "", sub(".*?\\.", "", i.l2))]]
    
    second.df <- cor.metab.ls[[sub("\\..*", "", i.l2)]]
    
    over.samp <- intersect(rownames(otu.tab), rownames(second.df))

    p.cor <- plot_bulk_corr(otu_tab = otu.tab[over.samp, ],
                          bulk_cor_res_long = res.long,
                          meta_data = ps.meta[over.samp, ],
                          second_df = second.df[over.samp, ],
                          strata_cols_meta = "Phenotype",
                          qval_cutoff = 0.1,
                          strip_text_size = 6)
    
    ggsave(paste0("out/fig/corr_plots/", 
                  gsub("--0", "", i.l2), ".png"), 
           p.cor, 
           width = 16, 
           height = ceiling(length(p.cor$layout$z)/4)*2, 
           limitsize = FALSE)

    strat.res.plots[[i.l2]] <- p.cor
  }

dir.create("out/fig/corr_plots")

```

